source "https://rubygems.org"
ruby "2.2.6"
gem "sinatra"
gem "sass"
gem "erb"
gem "dm-core"
gem "dm-migrations"
gem "thin"
gem "pg"
#gem "data_mapper"
gem "dm-postgres-adapter"
gem "dm-sqlite-adapter", :group => :development